import { useState } from 'react';
import LoomShell from '@/components/LoomShell';

export const route = { path: '/cluster', layout: 'owner', access: 'authenticated' };

export default function Cluster() {
  const [ttl, setTtl] = useState('24h');
  const [created, setCreated] = useState(false);
  return <LoomShell><div className="mx-auto max-w-3xl px-4 py-7 sm:px-6"><p className="font-mono text-[10px] uppercase tracking-[.2em] text-accent">SCREEN 09</p><h1 className="mt-1 font-heading text-3xl font-bold">Form encrypted cluster</h1><div className="mt-6 rounded-[16px] border border-border bg-card p-5"><h2 className="font-heading font-bold">Paired roster</h2><div className="mt-4 space-y-2">{['Tarek Mansour · RECON-4','Riya Sen · ALPHA-09'].map(name => <label key={name} className="flex items-center gap-3 rounded-lg border border-border p-3"><input type="checkbox" defaultChecked={name.startsWith('Tarek')} className="size-4 accent-primary"/><span className="text-sm font-semibold">{name}</span></label>)}</div><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-xs font-semibold">Frequency<select className="mt-2 w-full rounded-lg border border-border bg-background p-3 outline-none focus:ring-2 focus:ring-ring"><option>CH-08 · 2.4GHz</option><option>CH-11 · 5GHz</option></select></label><label className="text-xs font-semibold">Ephemeral TTL<select value={ttl} onChange={event => setTtl(event.target.value)} className="mt-2 w-full rounded-lg border border-border bg-background p-3 outline-none focus:ring-2 focus:ring-ring"><option value="1h">1 hour</option><option value="12h">12 hours</option><option value="24h">24 hours</option><option value="7d">7 days</option></select></label></div><div className="mt-6 rounded-xl bg-muted p-4"><p className="font-mono text-[9px] text-muted-foreground">MULTI-HOP RELAY</p><div className="mt-4 flex items-center justify-between font-mono text-[10px]"><span>YOU</span><span>↔</span><span>RECON-4</span><span>↔</span><span>RELAY-02</span></div></div><button type="button" onClick={() => setCreated(true)} className="mt-5 w-full rounded-lg bg-primary px-4 py-3 text-sm font-bold text-primary-foreground transition hover:opacity-90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">{created ? `Cluster live · TTL ${ttl}` : 'Create encrypted cluster'}</button></div></div></LoomShell>;
}
