import { useState } from 'react';
import LoomShell from '@/components/LoomShell';

export const route = { path: '/security', layout: 'owner', access: 'authenticated' };
export const nav = { icon: 'ShieldCheck', label: 'Security', section: 'Trust', order: 50, profiles: null };

export default function Security() {
  const [locked, setLocked] = useState(false);
  const [panic, setPanic] = useState(false);
  return <LoomShell><div className="mx-auto max-w-5xl px-4 py-7 sm:px-6"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-accent">SCREEN 14</p><h1 className="mt-1 font-heading text-3xl font-bold">Security center</h1><p className="mt-1 text-sm text-muted-foreground">The mesh exposes trust state, not private content, to unpaired relays.</p></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><article className="rounded-[16px] border border-border bg-card p-5"><div className="flex items-center justify-between"><h2 className="font-heading font-bold">Air-gapped audit</h2><span className="font-mono text-xs text-success">100%</span></div><div className="mt-4 h-3 rounded-full bg-secondary"><div className="h-3 w-full rounded-full bg-success"/></div><div className="mt-4 grid gap-2 font-mono text-[10px] text-muted-foreground"><span>✓ cloud route disabled</span><span>✓ double-ratchet cycling</span><span>✓ unpaired capability lock</span></div></article><article className="rounded-[16px] border border-border bg-card p-5"><h2 className="font-heading font-bold">Peer safety number</h2><p className="mt-2 text-xs text-muted-foreground">Compare this 60-digit fingerprint in person before sensitive use.</p><div className="mt-4 rounded-lg bg-muted p-4 font-mono text-xs leading-6">73102 94418 56021 88344 19027<br/>44107 62019 55182 70314 99205</div></article><article className="rounded-[16px] border border-border bg-card p-5 sm:col-span-2"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-heading font-bold">App lock & vault</h2><p className="mt-1 text-xs text-muted-foreground">Three failed PIN attempts purge volatile session material.</p></div><button type="button" onClick={() => setLocked(value => !value)} className="rounded-lg bg-primary px-4 py-3 text-xs font-bold text-primary-foreground transition hover:opacity-90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">{locked ? 'Unlock vault' : 'Lock vault'}</button></div></article><article className="rounded-[16px] border border-accent bg-card p-5 sm:col-span-2"><h2 className="font-heading font-bold">Emergency panic wipe</h2><p className="mt-1 text-xs text-muted-foreground">Simulated only: clears local demo state and returns to a blank decoy vault.</p><button type="button" onClick={() => setPanic(true)} className="mt-4 rounded-lg bg-accent px-4 py-3 text-xs font-bold text-accent-foreground transition hover:opacity-90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">Activate panic wipe</button>{panic && <p className="mt-3 font-mono text-xs text-accent">DECOY MODE ACTIVE · SESSION MATERIAL PURGED</p>}</article></div></div></LoomShell>;
}
