import { useState } from 'react';
import LoomShell from '@/components/LoomShell';

export const route = { path: '/status', layout: 'owner', access: 'authenticated' };
export const nav = { icon: 'RadioTower', label: 'Status', section: 'Mesh', order: 30, profiles: null };

export default function Status() {
  const [note, setNote] = useState('');
  const [published, setPublished] = useState(false);
  return <LoomShell><div className="mx-auto max-w-5xl px-4 py-7 sm:px-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="font-mono text-[10px] uppercase tracking-[.2em] text-accent">SCREEN 11</p><h1 className="mt-1 font-heading text-3xl font-bold">Tactical status</h1><p className="mt-1 text-sm text-muted-foreground">Paired-only broadcast. Auto-purges after 24 hours.</p></div><span className="rounded bg-success-muted px-3 py-2 font-mono text-[10px] text-success">PURGE IN 17:42:10</span></div><div className="mt-6 grid gap-4 lg:grid-cols-[1fr_1.2fr]"><section className="rounded-[16px] border border-border bg-card p-5"><p className="font-heading font-bold">Broadcast note</p><textarea value={note} onChange={event => setNote(event.target.value)} placeholder="Share a short local status…" className="mt-3 min-h-32 w-full resize-none rounded-lg border border-border bg-background p-3 text-sm outline-none focus:ring-2 focus:ring-ring"/><button type="button" onClick={() => { setPublished(true); setNote(''); setTimeout(() => setPublished(false), 1800); }} className="mt-3 w-full rounded-lg bg-primary px-4 py-3 text-sm font-bold text-primary-foreground transition hover:opacity-90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">{published ? 'Broadcast sent' : 'Broadcast to paired nodes'}</button></section><section className="space-y-3"><article className="rounded-[16px] border border-border bg-card p-5"><div className="flex justify-between"><div><p className="font-mono text-[9px] text-accent">CHECKPOINT · 16:48</p><h2 className="mt-1 font-heading font-bold">North ridge clear</h2></div><span className="rounded bg-success-muted px-2 py-1 font-mono text-[9px] text-success">PAIRED</span></div><p className="mt-3 text-sm leading-6 text-muted-foreground">Terrain is dry. Relay 02 is at 68% battery. Waypoint cached locally.</p></article><article className="rounded-[16px] border border-border bg-card p-5"><div className="flex justify-between"><div><p className="font-mono text-[9px] text-accent">VOICE MEMO · 15:22</p><h2 className="mt-1 font-heading font-bold">Relay diagnostics</h2></div><span className="font-mono text-[10px]">0:31</span></div><div className="mt-4 h-2 rounded-full bg-secondary"><div className="h-2 w-3/5 rounded-full bg-primary"/></div></article></section></div></div></LoomShell>;
}
